
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "fs";
import * as dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

const envFile = fs.existsSync(".env.local") ? ".env.local" : ".env";
dotenv.config({ path: envFile });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
