export const fallbackProperties = [
  {
    id: "sathorn-skyline-2br",
    title: "Sathorn skyline condo near BTS",
    description: "A bright two-bedroom condo with skyline views, secure entry, and quick access to BTS stations.",
    price: 42000,
    currency: "THB",
    propertyType: "CONDO",
    bedrooms: 2,
    bathrooms: 2,
    sizeSqm: 72,
    address: "Sathorn, Bangkok",
    township: "Sathorn",
    province: "Bangkok",
    country: "Thailand",
    latitude: null,
    longitude: null,
    nearestStation: "BTS Chong Nonsi",
    distanceToStation: null,
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    isFeatured: true,
    expiresAt: null,
    lastConfirmedAt: null,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: new Date("2026-01-01T00:00:00.000Z"),
    agentId: "demo-agent",
    images: [
      {
        id: "sathorn-cover",
        imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
        altText: "Sathorn skyline condo living room",
        displayOrder: 0,
        createdAt: new Date("2026-01-01T00:00:00.000Z"),
        propertyId: "sathorn-skyline-2br"
      }
    ],
    agent: { id: "demo-agent", name: "Demo Agent", phoneNumber: null },
    amenities: []
  },
  {
    id: "phrom-phong-studio",
    title: "Bright studio beside Phrom Phong",
    description: "Compact studio apartment near shopping, dining, and transport in central Bangkok.",
    price: 23000,
    currency: "THB",
    propertyType: "APARTMENT",
    bedrooms: 1,
    bathrooms: 1,
    sizeSqm: 38,
    address: "Watthana, Bangkok",
    township: "Watthana",
    province: "Bangkok",
    country: "Thailand",
    latitude: null,
    longitude: null,
    nearestStation: "BTS Phrom Phong",
    distanceToStation: null,
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    isFeatured: true,
    expiresAt: null,
    lastConfirmedAt: null,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: new Date("2026-01-01T00:00:00.000Z"),
    agentId: "demo-agent",
    images: [
      {
        id: "phrom-phong-cover",
        imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
        altText: "Bright studio bedroom",
        displayOrder: 0,
        createdAt: new Date("2026-01-01T00:00:00.000Z"),
        propertyId: "phrom-phong-studio"
      }
    ],
    agent: { id: "demo-agent", name: "Demo Agent", phoneNumber: null },
    amenities: []
  },
  {
    id: "rawai-villa-pool",
    title: "Private pool villa in Rawai",
    description: "A private villa with pool, outdoor space, and room for longer stays in Phuket.",
    price: 88000,
    currency: "THB",
    propertyType: "VILLA",
    bedrooms: 3,
    bathrooms: 3,
    sizeSqm: 210,
    address: "Rawai, Phuket",
    township: "Rawai",
    province: "Phuket",
    country: "Thailand",
    latitude: null,
    longitude: null,
    nearestStation: null,
    distanceToStation: null,
    status: "AVAILABLE",
    verificationStatus: "VERIFIED",
    isFeatured: true,
    expiresAt: null,
    lastConfirmedAt: null,
    createdAt: new Date("2026-01-01T00:00:00.000Z"),
    updatedAt: new Date("2026-01-01T00:00:00.000Z"),
    agentId: "demo-agent",
    images: [
      {
        id: "rawai-cover",
        imageUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80",
        altText: "Private pool villa",
        displayOrder: 0,
        createdAt: new Date("2026-01-01T00:00:00.000Z"),
        propertyId: "rawai-villa-pool"
      }
    ],
    agent: { id: "demo-agent", name: "Demo Agent", phoneNumber: null },
    amenities: []
  }
];
